package com.tammy.ourpage.dao;

import com.tammy.ourpage.model.Blog;

import java.util.List;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int deleteByPrimaryKey(Integer idblog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    Blog selectByPrimaryKey(Integer idblog);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int updateByPrimaryKey(Blog record);

    /**
     * get a blog page
     */
    List<Blog> selectBlogPage(Integer lastItemIndex,Integer numPerPage);



}