package com.tammy.ourpage.dao;

import com.tammy.ourpage.model.Type;

import java.util.List;

public interface TypeMapper {
    /**
     * 获得全部的类型
     * @return
     */
    List<Type> selectAllTypes();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int deleteByPrimaryKey(Integer idtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    Type selectByPrimaryKey(Integer idtype);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    int updateByPrimaryKey(Type record);
}