package com.tammy.ourpage.model;

import java.util.List;

public class Blog {
    public Blog(){
        this.title="";
        this.content="";
        this.typeID=-1;
        this.isTop=false;
        this.privacy=Privacy.ALL.getValue();
        this.thumbCount=0;
        this.time=System.currentTimeMillis();
        this.readCount=0;
        this.prefID=-1;
        this.nextID=-1;
        this.authorID=-1;
        this.imgTitle="";

    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.idblog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer idblog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.typeID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer typeID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.isTop
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Boolean isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.privacy
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer privacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.thumbCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer thumbCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.time
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Long time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.readCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.prefID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer prefID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.nextID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer nextID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.authorID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer authorID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.imgTitle
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private String imgTitle;


    private String tagsID;


    //链表查询获得额外字段
    private String typeName;
    private List<Tag> tags;
    private String cleanedContent;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.idblog
     *
     * @return the value of blog.idblog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getIdblog() {
        return idblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.idblog
     *
     * @param idblog the value for blog.idblog
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setIdblog(Integer idblog) {
        this.idblog = idblog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.typeID
     *
     * @return the value of blog.typeID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getTypeID() {
        return typeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.typeID
     *
     * @param typeID the value for blog.typeID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setTypeID(Integer typeID) {
        this.typeID = typeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.isTop
     *
     * @return the value of blog.isTop
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.isTop
     *
     * @param isTop the value for blog.isTop
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.privacy
     *
     * @return the value of blog.privacy
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getPrivacy() {
        return privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.privacy
     *
     * @param privacy the value for blog.privacy
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setPrivacy(Integer privacy) {
        this.privacy = privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.thumbCount
     *
     * @return the value of blog.thumbCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getThumbCount() {
        return thumbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.thumbCount
     *
     * @param thumbCount the value for blog.thumbCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setThumbCount(Integer thumbCount) {
        this.thumbCount = thumbCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.time
     *
     * @return the value of blog.time
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.time
     *
     * @param time the value for blog.time
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.readCount
     *
     * @return the value of blog.readCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.readCount
     *
     * @param readCount the value for blog.readCount
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.prefID
     *
     * @return the value of blog.prefID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getPrefID() {
        return prefID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.prefID
     *
     * @param prefID the value for blog.prefID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setPrefID(Integer prefID) {
        this.prefID = prefID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.nextID
     *
     * @return the value of blog.nextID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getNextID() {
        return nextID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.nextID
     *
     * @param nextID the value for blog.nextID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setNextID(Integer nextID) {
        this.nextID = nextID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.authorID
     *
     * @return the value of blog.authorID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getAuthorID() {
        return authorID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.authorID
     *
     * @param authorID the value for blog.authorID
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setAuthorID(Integer authorID) {
        this.authorID = authorID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.imgTitle
     *
     * @return the value of blog.imgTitle
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public String getImgTitle() {
        return imgTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.imgTitle
     *
     * @param imgTitle the value for blog.imgTitle
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setImgTitle(String imgTitle) {
        this.imgTitle = imgTitle;
    }


    public String getTagsID(){
        return tagsID;
    }

    public void  setTagsID(String tagsID){
        this.tagsID = tagsID;
    }

    public String getTypeName(){
        return typeName;
    }

    public void setTypeName(String name){
        this.typeName = name;
    }

    public List<Tag> getTags(){
        return tags;
    }

    public void  setTags(List<Tag> tags){
        this.tags = tags;
    }

    public String getCleanedContent(){
        return cleanedContent;
    }

    public void setCleanedContent(String cleanedContent){
        this.cleanedContent = cleanedContent;
    }


}