package com.tammy.ourpage.model;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.idtag
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer idtag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.idtag
     *
     * @return the value of tag.idtag
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getIdtag() {
        return idtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.idtag
     *
     * @param idtag the value for tag.idtag
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setIdtag(Integer idtag) {
        this.idtag = idtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tname
     *
     * @return the value of tag.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tname
     *
     * @param tname the value for tag.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setTname(String tname) {
        this.tname = tname;
    }
}