package com.tammy.ourpage.model;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.idtype
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private Integer idtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.idtype
     *
     * @return the value of type.idtype
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public Integer getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.idtype
     *
     * @param idtype the value for type.idtype
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tname
     *
     * @return the value of type.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tname
     *
     * @param tname the value for type.tname
     *
     * @mbggenerated Sat May 07 14:32:37 JST 2016
     */
    public void setTname(String tname) {
        this.tname = tname;
    }
}